# model definitions ----------------------

Page:
  columns:
    id:                           { type: integer, primary: true, autoincrement: true }  
    # link this into the sitetree
    sitetree_id:                  { type: integer, notnull: true }
    # the name of the template we're using
    template:                     { type: string, size: 50, notnull: true }
    # This is the content block group being used to render this page
    content_group_id:             { type: integer }
  
  indexes:
    site_route:
      fields: route_name
      type: unique
      
  relations:
    ContentGroup:
      class: ContentGroup
      local: content_group_id
      foreign: id
      type: one
    sitetree:
      class: Sitetree
      local: sitetree_id
      foreign: id
      type: one
      onDelete: NO ACTION
    
  actAs:
    Timestampable:          # created_at and updated_at
    Blameable:              # created_by and updated_by (override to use sfGuardUser)
      listener: siteBlamableListener

  options:
    symfony:                # some classes don't need these
      filter: false
      #form: false